spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: '022388'
    url: jdbc:mysql://localhost:3306/zhongchou

mybatis:
  type-aliases-package: com.qf.pojo